default: &default
 adapter: postgresql
 encoding: unicode
 pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
 <<: *default
 database: hailDatinV3_development

test:
 <<: *default
 database: hailDatinV3_test

production:
 <<: *default
 database: hailDatinV3_production
 username: hailDatinV3
 password: <%= ENV['HAILDATINV3_DATABASE_PASSWORD'] %>

# Code for testing using postgreSQL on your local machine
#
# default: &default
#  adapter: postgresql
#  encoding: unicode
#  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  username: postgres
#  password: whateverpostgresqlpasswordis
#
# development:
#  <<: *default
#  database: hailDatinV3_development
#
# test:
#  <<: *default
#  database: hailDatinV3_test
#
# production:
#  <<: *default
#  database: hailDatinV3_production
